import { createRouter } from './router/router.js';
import { registerSystemRoutes } from './modules/system/system.routes.js';
import { registerLoginConfigShadowRoute } from './modules/system/login-config.routes.js';
import { registerFrontendRoutes } from './modules/frontend/frontend.routes.js';
import { registerConsoleSummaryShadowRoute } from './modules/console/console-summary.routes.js';
import { registerCalendarEventsShadowRoute } from './modules/calendar/calendar-events.routes.js';
import { registerKnowledgeReadShadowRoutes } from './modules/knowledge/knowledge-read.routes.js';
import { registerAiWearPublicShadowRoute } from './modules/ai-wear/ai-wear-public.routes.js';
import { registerAiWearGalleryShadowRoute } from './modules/ai-wear/ai-wear-gallery.routes.js';
import { registerAiWearResultsShadowRoute } from './modules/ai-wear/ai-wear-results.routes.js';
import { registerAiWearCostSummaryShadowRoute } from './modules/ai-wear/ai-wear-cost-summary.routes.js';
import { registerAiWearSettingsShadowRoute } from './modules/ai-wear/ai-wear-settings.routes.js';
import { registerAiWearShareCardShadowRoute } from './modules/ai-wear/ai-wear-share-card.routes.js';
import { registerCheckinTemplateShadowRoute } from './modules/checkin/checkin-template.routes.js';
import { registerReplyLearningShadowRoute } from './modules/reply-learning/reply-learning.routes.js';
import { registerFloorWhitelistShadowRoute } from './modules/access/floor-whitelist.routes.js';
import { registerRewardConfigShadowRoute } from './modules/reward/reward-config.routes.js';
import { registerRewardCalendarEventsShadowRoute } from './modules/reward/reward-calendar-events.routes.js';
import { registerPointObservationsShadowRoute } from './modules/points/point-observations.routes.js';
import { legacyFetch } from './legacy/legacy-fetch.js';
import { createApp } from './app.js';

const router = createRouter();
registerSystemRoutes(router);
registerLoginConfigShadowRoute(router, { legacyFetch });
registerFrontendRoutes(router);
registerConsoleSummaryShadowRoute(router, { legacyFetch });
registerCalendarEventsShadowRoute(router, { legacyFetch });
registerKnowledgeReadShadowRoutes(router, { legacyFetch });
registerAiWearPublicShadowRoute(router, { legacyFetch });
registerAiWearGalleryShadowRoute(router, { legacyFetch });
registerAiWearResultsShadowRoute(router, { legacyFetch });
registerAiWearCostSummaryShadowRoute(router, { legacyFetch });
registerAiWearSettingsShadowRoute(router, { legacyFetch });
registerAiWearShareCardShadowRoute(router, { legacyFetch });
registerCheckinTemplateShadowRoute(router, { legacyFetch });
registerReplyLearningShadowRoute(router, { legacyFetch });
registerFloorWhitelistShadowRoute(router, { legacyFetch });
registerRewardConfigShadowRoute(router, { legacyFetch });
registerRewardCalendarEventsShadowRoute(router, { legacyFetch });
registerPointObservationsShadowRoute(router, { legacyFetch });

export { createApp } from './app.js';
export { createRouter } from './router/router.js';
export { registerSystemRoutes } from './modules/system/system.routes.js';
export { registerLoginConfigShadowRoute } from './modules/system/login-config.routes.js';
export { registerFrontendRoutes } from './modules/frontend/frontend.routes.js';
export { registerConsoleSummaryShadowRoute } from './modules/console/console-summary.routes.js';
export { registerCalendarEventsShadowRoute } from './modules/calendar/calendar-events.routes.js';
export { registerKnowledgeReadShadowRoutes } from './modules/knowledge/knowledge-read.routes.js';
export { registerAiWearPublicShadowRoute } from './modules/ai-wear/ai-wear-public.routes.js';
export { registerAiWearGalleryShadowRoute } from './modules/ai-wear/ai-wear-gallery.routes.js';
export { registerAiWearResultsShadowRoute } from './modules/ai-wear/ai-wear-results.routes.js';
export { registerAiWearCostSummaryShadowRoute } from './modules/ai-wear/ai-wear-cost-summary.routes.js';
export { registerAiWearSettingsShadowRoute } from './modules/ai-wear/ai-wear-settings.routes.js';
export { registerAiWearShareCardShadowRoute } from './modules/ai-wear/ai-wear-share-card.routes.js';
export { registerCheckinTemplateShadowRoute } from './modules/checkin/checkin-template.routes.js';
export { registerReplyLearningShadowRoute } from './modules/reply-learning/reply-learning.routes.js';
export { registerFloorWhitelistShadowRoute } from './modules/access/floor-whitelist.routes.js';
export { registerRewardConfigShadowRoute } from './modules/reward/reward-config.routes.js';
export { registerRewardCalendarEventsShadowRoute } from './modules/reward/reward-calendar-events.routes.js';
export { registerPointObservationsShadowRoute } from './modules/points/point-observations.routes.js';

export default createApp({ router, legacyFetch });